### ISSUE TITLE
Mark query parameters as optional

### ISSUE THREAD

**Issue by Jameskmonger** [simplyspoke/node-harvest#114]
`requestGenerator` in `index.ts` has an optional parameter `data`:

```
return function(method: string, uri: string, data: any = {}) {
```

However, places that use this, for example `projectAssignments.me` do not mark this parameter as optional:

```
public me(query: PagenationParameters) {
```

An obvious workaround is to do `me({})`, but it would be good to be able to just call `me()` and let the package handle the defaults

**Comment by simplyspoke** [comment]
I agree,

Should have some time this evening for a update.

Thanks for all the help and feedback on the module!

**Comment by Jameskmonger** [comment]
Thanks @simplyspoke :smile:
