### ISSUE TITLE
timeEntries.create parameters do not match API

### ISSUE THREAD

**Issue by Jameskmonger** [simplyspoke/node-harvest#115]
The below code works correctly, however it fails to compile in TypeScript

```
timeEntries.create({
    project_id: projectId,
    task_id: taskId,
    spent_date: date,
    notes: notes
});
```

It fails because `create` expects a `TimeEntry` parameter. The `TimeEntry` interface seems to match the `GET` requests perfectly but not the `POST`/`PUT` requests.

I suspect this issue extends to other entities as well.

**Comment by simplyspoke** [comment]
Any chance you have a sample of the use case? Thinking that would help me expedite a fix.

**Comment by Jameskmonger** [comment]
On the [Harvest API documentation](https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/#create-a-time-entry-via-duration) there are two signatures that can be used to create a time entry.

The first is with a date and duration:

```
interface CreateTimeEntryDuration {
    project_id: number;
    task_id: number;
    spent_date: string;
    
    user_id?: number;
    hours?: number;
    notes?: string;
    external_reference?: any;
}
```

The second is with a start time and an end time (the interface name here isn't great):

```
interface CreateTimeEntryTime {
    project_id: number;
    task_id: number;
    spent_date: string;
    
    user_id?: number;
    started_time?: string;
    ended_time?: string;
    notes?: string;
    external_reference?: any;
}
```

Currently, `timeEntries.create` doesn't match either of the signatures above, I think that it should be changed to:

```
public create(data: CreateTimeEntryDuration | CreateTimeEntryTime) {
```

**Comment by Jameskmonger** [comment]
@simplyspoke I've added a PR for this (#116)
