### ISSUE TITLE
query params on get request not working

### ISSUE THREAD

**Issue by iteratelance** [simplyspoke/node-harvest#219]
When using the API passing in GET query variables are not appended to the URL.

For example:
```js
harvest.users.list({is_active: true}).then((users) =>{})
```
and
```js
harvest.users.list('?is_active=true').then((users) =>{})
```

**Actual**
```json
  method: 'GET',
  uri: '/v2/users',
  body: '{"is_active":true}',
```

**Expected**
```json
  method: 'GET',
  uri: '/v2/users?is_active=true',
  body: '',
```
A proposed solution would be modifying RequestClient in client.js from
```js
    requestGenerator() {
        return (task, done) => {
            let options = {};
            options.method = task.method;
            options.uri = task.uri;
            options.body = JSON.stringify(task.data);
```
To
```js
    requestGenerator() {
        return (task, done) => {
            let options = {};
            options.method = task.method;
            options.uri = task.uri;
            
            if(task.method.toUpperCase() == 'GET'){
                options.qs = task.data;
            } else {
                options.body = JSON.stringify(task.data);
            }
```

Notice: https://github.com/request/request
`qs - object containing querystring values to be appended to the uri`

For anyone else struggling here I opted to use: https://www.npmjs.com/package/harvest-v2

**Comment by matthewjumpsoffbuildings** [comment]
I have the same issue, any word from the developer or do i also need to switch to harvest-v2

**Comment by simplyspoke** [comment]
It would be a good idea to try to work with the v2 package. The v1 is a bit dated at this point and Harvest did a lot in the v2 to cleanup the API.

If there are any issues in the v2 package, it should be short work to sort it there.
