### ISSUE TITLE
API v2 support

### ISSUE THREAD

**Issue by LTchrisb** [simplyspoke/node-harvest#75]
Is there a roadmap for migrating this library to support the new V2 api? 
https://help.getharvest.com/api-v2/introduction/overview/general/

**Comment by simplyspoke** [comment]
No roadmap at the moment. Once I get a free moment I can have a look at the next major release. With any luck they have cleaned up some of their not so restful endpoints.

**Comment by simplyspoke** [comment]
Thanks for mention this and sorry for the delay. I will try to start dedicating some time to planning for and developing a strategy for another release to bring this module up to date with v2 of the api.

I will reach-out and see if I can get a swagger file or something of the like to cover the full api in a easy to consume manor, then go from there. It might be feasible to look at a plan to form through Jan with a possible release candidate in Feb.

**Comment by dardub** [comment]
Hi, thanks for providing this! I see you've been working on v2 quite a bit and it looks close. Do you think it's ready for others to try? I understand the potential for bugs, etc.

**Comment by simplyspoke** [comment]
I just completed the preliminary development, but I have yet to begin effective testing of the wrapper. I am also considering making a few adjustments to some to the access patterns for different resources to make things a little more accessible.

Lets consider it to be pre-alpha at this state.

**Comment by simplyspoke** [comment]
@LTchrisb & @dardub 

The Harvest API v2 should now be accessible through the `harvest@2.0.0` There are some missing features and likely a few surprises, but I have brought unit tests up to complete coverage and integration has confirmed the true nature of the API, some required fields I need to let them know about.

Feel free to give it a try and flag any feature request or bugs in other issues.
