### ISSUE TITLE
type definition file not found

### ISSUE THREAD

**Issue by satoyan** [simplyspoke/node-harvest#94]
I'm using TypeScript and had tried to use this library.
package.json has typings like below
  "typings": "dist/types/harvest.d.ts",

But this file does net exists at ./node_modules/harvest/
So I had tried that wrote 3slash ref comment to reference *.d.ts file directly, but it didn't work.

**Comment by simplyspoke** [comment]
Thank you for reporting this issue. I will install the module into a clean project and work to recreate the issue.

**Comment by simplyspoke** [comment]
@satoyan The missing typings should now be repaired. Let me know if you have any further issues.

**Comment by satoyan** [comment]
Thank you for fixiing this!! :tada:
